{* templates/CRM/Memberperiodsterms/Page/MembershipPeriods.tpl
is loaded automatically after the controller executes. It defines the markup that is eventually displayed. *}
<h3>This new page is generated by CRM/Memberperiodsterms/Page/MembershipPeriods.php</h3>

{* Example: Display a variable directly *}
<p>The current time is {$currentTime}</p>

{* Example: Display a translated string -- which happens to include a variable *}
<p>{ts 1=$currentTime}(In your native language) The current time is %1.{/ts}</p>
